workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - lint

shellcheck:
  stage: lint
  image: registry.gitlab.com/pipeline-components/shellcheck:latest
  script:
    - shellcheck ./rofi-vpn
